import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { HomePage } from "./HomePage"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Welcome to our first own Pokédex</h2>

        <HomePage />
      </main>

      <footer className={styles.footer}>
        This was built with <a href="https://nextjs.org">Next.js!</a>
      </footer>
    </div>
  )
}

export default Home
